### ISSUE TITLE
Check status of 'wants Emails' for new users

### ISSUE THREAD

**Issue by aeythepa** [USEPA/emf#142]
I think the default status for receiving EMF update emails may be false for new users.  We should set it to true if it is not by default.

**Comment by cseppan** [comment]
When a new user registers or an admin creates a new user, the option "Receives EMF update emails?" is checked by default. A new user can opt out immediately if they like.

<img width="421" alt="Screenshot 2024-03-28 at 2 07 16 PM" src="https://github.com/USEPA/emf/assets/7329179/f6bc9987-585c-4e9c-9f82-c085c02c2983">

I've also been turning off the Wants Emails flag for any users where I get a bounce message when sending EMF updates (usually because they're not with EPA anymore). Now that we have the account disable option, we can just disable these old accounts.
